export const CF_BUTTON_ACESSAR = 'CF_BUTTON_ACESSAR';
export const CF_BUTTON_CANCELAR = 'CF_BUTTON_CANCELAR';
export const CF_BUTTON_VOLTAR = 'CF_BUTTON_VOLTAR';
export const CF_BUTTON_MODAL_ALTERAR = 'CF_BUTTON_MODAL_ALTERAR';
export const CF_BUTTON_MODAL_CANCELAR = 'CF_BUTTON_MODAL_CANCELAR';
export const CF_BUTTON_CONTINUAR = 'CF_BUTTON_CONTINUAR';
