export enum CamposParecerEnum {
  formacaoHomologada = 1,
  tipoFormacao = 2,
  formato = 3,
  tiposInscricao = 4,
  integrarNoSGA = 5,
  dres = 6,
  nomeFormacao = 7,
  publicosAlvo = 8,
  funcoesEspecificas = 9,
  modalidade = 10,
  anosTurmas = 11,
  componentesCurriculares = 12,
  criteriosValidacaoInscricao = 13,
  vagasRemanecentes = 14,
  quantidadeTurmas = 15,
  quantidadeVagasTurma = 16,
  cargaHoraria = 17,
  justificativa = 18,
  objetivos = 19,
  conteudoProgramatico = 20,
  procedimentoMetadologico = 21,
  referencia = 22,
  palavrasChaves = 23,
  periodoRealizacao = 24,
  periodoInscricao = 25,
  cursoComCertificado = 26,
  criterioCertificacao = 27,
  descricaoDaAtividade = 28,
  codigoEventoSigpec = 29,
  linkParaInscricoesExterna = 30,
}

export const CamposParecerEnumDisplay: Record<CamposParecerEnum, string> = {
  [CamposParecerEnum.formacaoHomologada]: 'Formação homologada por SME/COPED/DF',
  [CamposParecerEnum.tipoFormacao]: 'Tipo de formação',
  [CamposParecerEnum.formato]: 'Modalidade formativa',
  [CamposParecerEnum.tiposInscricao]: 'Tipos de inscrição',
  [CamposParecerEnum.integrarNoSGA]: 'Integrar no SGA',
  [CamposParecerEnum.dres]: 'DRE',
  [CamposParecerEnum.nomeFormacao]: 'Nome da formação',
  [CamposParecerEnum.publicosAlvo]: 'Público alvo',
  [CamposParecerEnum.funcoesEspecificas]: 'Função específica',
  [CamposParecerEnum.modalidade]: 'Etapa/Modalidade',
  [CamposParecerEnum.anosTurmas]: 'Ano/Etapa',
  [CamposParecerEnum.componentesCurriculares]: 'Componente Curricular',
  [CamposParecerEnum.criteriosValidacaoInscricao]: 'Critérios para validação das inscrições',
  [CamposParecerEnum.vagasRemanecentes]: 'Em caso de vagas remanescentes',
  [CamposParecerEnum.quantidadeTurmas]: 'Quantidade de turmas',
  [CamposParecerEnum.quantidadeVagasTurma]: 'Vagas por turma',
  [CamposParecerEnum.cargaHoraria]: 'Carga horária',
  [CamposParecerEnum.justificativa]: 'Justificativa',
  [CamposParecerEnum.objetivos]: 'Objetivos',
  [CamposParecerEnum.conteudoProgramatico]: 'Conteúdo programático',
  [CamposParecerEnum.procedimentoMetadologico]: 'Procedimentos metodológicos',
  [CamposParecerEnum.referencia]: 'Referências',
  [CamposParecerEnum.palavrasChaves]: 'Palavras-chave',
  [CamposParecerEnum.periodoRealizacao]: 'Período de realização',
  [CamposParecerEnum.periodoInscricao]: 'Período de inscrição',
  [CamposParecerEnum.cursoComCertificado]: 'Curso com certificação',
  [CamposParecerEnum.criterioCertificacao]: 'Critérios para certificação',
  [CamposParecerEnum.descricaoDaAtividade]: 'Descrição da atividade obrigatória para certificação',
  [CamposParecerEnum.codigoEventoSigpec]: 'Código do Evento (SIGPEC)',
  [CamposParecerEnum.linkParaInscricoesExterna]: 'Link para Inscrições',
};

export const CamposParecerNomeEnumDisplay: Record<CamposParecerEnum, string> = {
  [CamposParecerEnum.formacaoHomologada]: 'formacaoHomologada',
  [CamposParecerEnum.tipoFormacao]: 'tipoFormacao',
  [CamposParecerEnum.formato]: 'formato',
  [CamposParecerEnum.tiposInscricao]: 'tiposInscricao',
  [CamposParecerEnum.integrarNoSGA]: 'integrarNoSGA',
  [CamposParecerEnum.dres]: 'dres',
  [CamposParecerEnum.nomeFormacao]: 'nomeFormacao',
  [CamposParecerEnum.publicosAlvo]: 'publicosAlvo',
  [CamposParecerEnum.funcoesEspecificas]: 'funcoesEspecificas',
  [CamposParecerEnum.modalidade]: 'modalidade',
  [CamposParecerEnum.anosTurmas]: 'anosTurmas',
  [CamposParecerEnum.componentesCurriculares]: 'componentesCurriculares',
  [CamposParecerEnum.criteriosValidacaoInscricao]: 'criteriosValidacaoInscricao',
  [CamposParecerEnum.vagasRemanecentes]: 'vagasRemanecentes',
  [CamposParecerEnum.quantidadeTurmas]: 'quantidadeTurmas',
  [CamposParecerEnum.quantidadeVagasTurma]: 'quantidadeVagasTurma',
  [CamposParecerEnum.cargaHoraria]: 'cargaHoraria',
  [CamposParecerEnum.justificativa]: 'justificativa',
  [CamposParecerEnum.objetivos]: 'objetivos',
  [CamposParecerEnum.conteudoProgramatico]: 'conteudoProgramatico',
  [CamposParecerEnum.procedimentoMetadologico]: 'procedimentoMetadologico',
  [CamposParecerEnum.referencia]: 'referencia',
  [CamposParecerEnum.palavrasChaves]: 'palavrasChaves',
  [CamposParecerEnum.periodoRealizacao]: 'periodoRealizacao',
  [CamposParecerEnum.periodoInscricao]: 'periodoInscricao',
  [CamposParecerEnum.cursoComCertificado]: 'cursoComCertificado',
  [CamposParecerEnum.criterioCertificacao]: 'criterioCertificacao',
  [CamposParecerEnum.descricaoDaAtividade]: 'descricaoDaAtividade',
  [CamposParecerEnum.codigoEventoSigpec]: 'codigoEventoSigpec',
  [CamposParecerEnum.linkParaInscricoesExterna]: 'linkParaInscricoesExterna',
};
