export enum MenuEnum {
  Principal = 1,
  MeusDados,
  Cadastros,
  AreaPromotora,
  CadastroProposta,
  Formacoes,
  Inscricoes,
  RedeParceria,
  ListaPresencaCodaf,
  CodafFormacoesHomologadas,
  CodafFormacoesNaoHomologadas,
  Certificados,
  CertificadosPesquisa,
  Relatorios,
  RelatorioInscritosPorFormacao,
  Coordenadoria,
  CodafSuplementar,
}
