export enum ROUTES {
  PRINCIPAL = '/',
  LOGIN = '/login',
  LOGIN_AUTOMATICO_PELO_TOKEN = '/login/:token',
  CADASTRO_DE_USUARIO = '/cadastre-se',
  MEUS_DADOS = '/meus-dados',
  REDEFINIR_SENHA = '/redefinir-senha',
  REDEFINIR_SENHA_TOKEN = '/redefinir-senha/:token',
  CADASTRO = '/cadastro',
  CADASTRO_DE_PROPOSTAS = '/cadastro/cadastro-de-propostas',
  CADASTRO_DE_PROPOSTAS_NOVO = '/cadastro/cadastro-de-propostas/novo',
  CADASTRO_DE_PROPOSTAS_EDITAR = '/cadastro/cadastro-de-propostas/editar/:id',
  AREA_PROMOTORA = '/cadastro/area-promotora',
  AREA_PROMOTORA_NOVO = '/cadastro/area-promotora/novo',
  AREA_PROMOTORA_EDITAR = '/cadastro/area-promotora/editar/:id',
  SEM_PERMISSAO = '/sem-permissao',
  AREA_PUBLICA = '/area-publica',
  AREA_PUBLICA_VISUALIZAR_FORMACAO = '/area-publica/visualizar/:id',
  INSCRICAO = '/inscricao',
  FORMACAOES_INSCRICOES = '/formacoes/inscricoes',
  FORMACAOES_INSCRICOES_EDITAR = '/formacoes/inscricoes/editar/:id',
}
