export enum SituacaoProposta {
  Publicada = 1,
  Rascunho = 2,
  Cadastrada = 3,
  AguardandoAnaliseDf = 4,
  AguardandoAnaliseGestao = 5,
  Desfavoravel = 6,
  Devolvida = 7,
  Alterando = 8,
  Aprovada = 9,
  AguardandoAnalisePeloParecerista = 10,
  AguardandoAnaliseParecerPelaDF = 11,
  AnaliseParecerPelaAreaPromotora = 12,
  Recusada = 13,
  AguardandoReanalisePeloParecerista = 14,
  AguardandoAnaliseParecerFinalPelaDF = 15,
}

export const SituacaoPropostaTagDisplay: Record<SituacaoProposta, string> = {
  [SituacaoProposta.Publicada]: 'Publicada',
  [SituacaoProposta.Rascunho]: 'Rascunho',
  [SituacaoProposta.Cadastrada]: 'Cadastrada',
  [SituacaoProposta.AguardandoAnaliseDf]: 'Aguardando análise da DF',
  [SituacaoProposta.AguardandoAnaliseGestao]: 'Aguardando análise da gestão',
  [SituacaoProposta.Desfavoravel]: 'Desfavorável',
  [SituacaoProposta.Devolvida]: 'Devolvida',
  [SituacaoProposta.Alterando]: 'Alterando',
  [SituacaoProposta.Aprovada]: 'Aprovada',
  [SituacaoProposta.AguardandoAnalisePeloParecerista]: 'Aguardando análise do Parecerista',
  [SituacaoProposta.AguardandoAnaliseParecerPelaDF]: 'Aguardando análise do parecer pela DF',
  [SituacaoProposta.AnaliseParecerPelaAreaPromotora]: 'Análise do parecer pela área promotora',
  [SituacaoProposta.Recusada]: 'Recusada',
  [SituacaoProposta.AguardandoReanalisePeloParecerista]: 'Aguardando reanálise do Parecerista',
  [SituacaoProposta.AguardandoAnaliseParecerFinalPelaDF]: 'Aguardando validação final pela DF',
};
