export const CF_INPUT_LOGIN = 'CF_INPUT_LOGIN';
export const CF_INPUT_SENHA = 'CF_INPUT_SENHA';
export const CF_INPUT_EMAIL = 'CF_INPUT_EMAIL';
export const CF_INPUT_SENHA_ATUAL = 'CF_INPUT_SENHA_ATUAL';
export const CF_INPUT_CONFIRMAR_SENHA = 'CF_INPUT_CONFIRMAR_SENHA';
export const CF_INPUT_NOME = 'CF_INPUT_NOME';
export const CF_INPUT_TELEFONE = 'CF_INPUT_TELEFONE';
export const CF_INPUT_TOTAL_VAGAS = 'CF_INPUT_TOTAL_VAGAS';
export const CF_INPUT_NOME_FORMACAO = 'CF_INPUT_NOME_FORMACAO';
export const CF_INPUT_CRITERIOS_VALIDACOES_INSCRICAO_OUTROS =
  'CF_INPUT_CRITERIOS_VALIDACOES_INSCRICAO_OUTROS';
export const CF_INPUT_FUNCAO_ESPECIFICA_OUTROS = 'CF_INPUT_FUNCAO_ESPECIFICA_OUTROS';
export const CF_INPUT_QUANTIDADE_TURMAS = 'CF_INPUT_QUANTIDADE_TURMAS';
export const CF_INPUT_QUANTIDADE_VAGAS_TURMA = 'CF_INPUT_QUANTIDADE_VAGAS_TURMA';
