const CF_INPUT_LOGIN = 'CF_INPUT_LOGIN';
const CF_INPUT_CPF = 'CF_INPUT_LOGIN';
const CF_INPUT_SENHA = 'CF_INPUT_SENHA';
const CF_INPUT_EMAIL = 'CF_INPUT_EMAIL';
const CF_INPUT_UNIDADE = 'CF_INPUT_UNIDADE';
const CF_INPUT_EMAIL_EDUCACIONAL = 'CF_INPUT_EMAIL';
const CF_INPUT_CONFIRMAR_EMAIL = 'CF_INPUT_CONFIRMAR_EMAIL';
const CF_INPUT_SENHA_ATUAL = 'CF_INPUT_SENHA_ATUAL';
const CF_INPUT_CONFIRMAR_SENHA = 'CF_INPUT_CONFIRMAR_SENHA';
const CF_INPUT_NOME = 'CF_INPUT_NOME';
const CF_INPUT_NOME_UE = 'CF_INPUT_NOME_UE';
const CF_INPUT_UE = 'CF_INPUT_UE';
const CF_INPUT_TELEFONE = 'CF_INPUT_TELEFONE';
const CF_INPUT_TOTAL_VAGAS = 'CF_INPUT_TOTAL_VAGAS';
const CF_INPUT_NOME_FORMACAO = 'CF_INPUT_NOME_FORMACAO';
const CF_INPUT_TIPO_NOTIFICACAO = 'CF_INPUT_TIPO_NOTIFICACAO';
const CF_INPUT_CATEGORIA_NOTIFICACAO = 'CF_INPUT_CATEGORIA_NOTIFICACAO';
const CF_INPUT_TITULO_NOTIFICACAO = 'CF_INPUT_TITULO_NOTIFICACAO';
const CF_INPUT_SITUACAO_NOTIFICACAO = 'CF_INPUT_SITUACAO_NOTIFICACAO';
const CF_INPUT_CRITERIOS_VALIDACOES_INSCRICAO_OUTROS =
  'CF_INPUT_CRITERIOS_VALIDACOES_INSCRICAO_OUTROS';
const CF_INPUT_CRITERIOS_CERTIFICACAO_INSCRICAO_OUTROS =
  'CF_INPUT_CRITERIOS_CERTIFICACAO_INSCRICAO_OUTROS';
const CF_INPUT_FUNCAO_ESPECIFICA_OUTROS = 'CF_INPUT_FUNCAO_ESPECIFICA_OUTROS';
const CF_INPUT_PUBLICO_ALVO_OUTROS = 'CF_INPUT_PUBLICO_ALVO_OUTROS';
const CF_INPUT_ANO_ETAPA_TODOS = 'CF_INPUT_ANO_ETAPA_TODOS';
const CF_INPUT_COMPONENTE_CURRICULAR_TODOS = 'CF_INPUT_COMPONENTE_CURRICULAR_TODOS';
const CF_INPUT_QUANTIDADE_TURMAS = 'CF_INPUT_QUANTIDADE_TURMAS';
const CF_INPUT_QUANTIDADE_VAGAS_TURMA = 'CF_INPUT_QUANTIDADE_VAGAS_TURMA';
const CF_INPUT_CODIGO_NOTIFICACAO = 'CF_INPUT_CODIGO_NOTIFICACAO';
const CF_INPUT_CODIGO_FORMACAO = 'CF_INPUT_CODIGO_FORMACAO';
const CF_INPUT_CODIGO_EOL = 'CF_INPUT_CODIGO_EOL';
const CF_INPUT_NUMERO_HOMOLOGACAO = 'CF_INPUT_NUMERO_HOMOLOGACAO';
const CF_INPUT_PERIODO_INICIO = 'CF_INPUT_PERIODO_INICIO';
const CF_INPUT_PERIODO_FIM = 'CF_INPUT_PERIODO_FIM';
const CF_INPUT_DATA = 'CF_INPUT_DATA';
const CF_INPUT_RF = 'CF_INPUT_RF';
const CF_INPUT_AREA_TEXTO = 'CF_INPUT_AREA_TEXTO';
const CF_INPUT_TEXT_AREA = 'CF_INPUT_AREA_TEXTO';
const CF_INPUT_LINK_INSCRICOES_EXTERNA = 'CF_INPUT_LINK_INSCRICOES_EXTERNA';

export {
  CF_INPUT_ANO_ETAPA_TODOS,
  CF_INPUT_AREA_TEXTO,
  CF_INPUT_CATEGORIA_NOTIFICACAO,
  CF_INPUT_CODIGO_EOL,
  CF_INPUT_CODIGO_FORMACAO,
  CF_INPUT_CODIGO_NOTIFICACAO,
  CF_INPUT_COMPONENTE_CURRICULAR_TODOS,
  CF_INPUT_CONFIRMAR_EMAIL,
  CF_INPUT_CONFIRMAR_SENHA,
  CF_INPUT_CPF,
  CF_INPUT_CRITERIOS_CERTIFICACAO_INSCRICAO_OUTROS,
  CF_INPUT_CRITERIOS_VALIDACOES_INSCRICAO_OUTROS,
  CF_INPUT_DATA,
  CF_INPUT_EMAIL,
  CF_INPUT_EMAIL_EDUCACIONAL,
  CF_INPUT_FUNCAO_ESPECIFICA_OUTROS,
  CF_INPUT_LINK_INSCRICOES_EXTERNA,
  CF_INPUT_LOGIN,
  CF_INPUT_NOME,
  CF_INPUT_NOME_FORMACAO,
  CF_INPUT_NOME_UE,
  CF_INPUT_NUMERO_HOMOLOGACAO,
  CF_INPUT_PERIODO_FIM,
  CF_INPUT_PERIODO_INICIO,
  CF_INPUT_PUBLICO_ALVO_OUTROS,
  CF_INPUT_QUANTIDADE_TURMAS,
  CF_INPUT_QUANTIDADE_VAGAS_TURMA,
  CF_INPUT_RF,
  CF_INPUT_SENHA,
  CF_INPUT_SENHA_ATUAL,
  CF_INPUT_SITUACAO_NOTIFICACAO,
  CF_INPUT_TELEFONE,
  CF_INPUT_TEXT_AREA,
  CF_INPUT_TIPO_NOTIFICACAO,
  CF_INPUT_TITULO_NOTIFICACAO,
  CF_INPUT_TOTAL_VAGAS,
  CF_INPUT_UE,
  CF_INPUT_UNIDADE,
};
