export const CF_INPUT_LOGIN = 'CF_INPUT_LOGIN';
export const CF_INPUT_SENHA = 'CF_INPUT_SENHA';
export const CF_INPUT_EMAIL = 'CF_INPUT_EMAIL';
export const CF_INPUT_SENHA_ATUAL = 'CF_INPUT_SENHA_ATUAL';
export const CF_INPUT_CONFIRMAR_SENHA = 'CF_INPUT_CONFIRMAR_SENHA';
export const CF_INPUT_NOME = 'CF_INPUT_NOME';
export const CF_INPUT_TELEFONE = 'CF_INPUT_TELEFONE';
