export const CF_RADIO_TIPO_FORMACAO = 'CF_RADIO_TIPO_FORMACAO';
export const CF_RADIO_TIPO_INSCRICAO = 'CF_RADIO_TIPO_INSCRICAO';
export const CF_RADIO_FORMACAO_HOMOLOGADA = 'CF_RADIO_FORMACAO_HOMOLOGADA';
export const CF_RADIO_SIM_NAO = 'CF_RADIO_SIM_NAO';
export const CF_RADIO_PROFISSIONAL_REDE_MUNICIPAL = 'CF_RADIO_PROFISSIONAL_REDE_MUNICIPAL';
export const CF_RADIO_INTEGRA_NO_SGA = 'CF_RADIO_INTEGRA_NO_SGA';
