export const CF_RADIO_TIPO_FORMACAO = 'CF_RADIO_TIPO_FORMACAO';
export const CF_RADIO_TIPO_INSCRICAO = 'CF_RADIO_TIPO_INSCRICAO';
export const CF_RADIO_FORMACAO_HOMOLOGADA = 'CF_RADIO_FORMACAO_HOMOLOGADA';
