const CF_SELECT_FORMATO = 'CF_SELECT_FORMATO';
const CF_SELECT_ANO_ETAPA = 'CF_SELECT_ANO_ETAPA';
const CF_SELECT_COMPONENTE_CURRICULAR = 'CF_SELECT_COMPONENTE_CURRICULAR';
const CF_SELECT_MODALIDADE = 'CF_SELECT_MODALIDADE';
const CF_SELECT_PUBLICO_ALVO = 'CF_SELECT_PUBLICO_ALVO';
const CF_SELECT_FUNCAO_ESPECIFICA = 'CF_SELECT_FUNCAO_ESPECIFICA';
const CF_SELECT_CRITERIOS_VALIDACOES_INSCRICAO = 'CF_SELECT_CRITERIOS_VALIDACOES_INSCRICAO';
const CF_SELECT_VAGAS_REMANESCENTES = 'CF_SELECT_VAGAS_REMANESCENTES';
const CF_SELECT_AREA_PROMOTORA = 'CF_SELECT_AREA_PROMOTORA';
const CF_SELECT_SITUACAO = 'CF_SELECT_SITUACAO';
const CF_SELECT_TURMA_CRONOGRAMA = 'CF_SELECT_TURMA_CRONOGRAMA';
const CF_SELECT_TURMA_INSCRICAO = 'CF_SELECT_TURMA_INSCRICAO';
const CF_SELECT_CARGO = 'CF_SELECT_CARGO';
const CF_SELECT_FUNCAO_ATIVIDADE = 'CF_SELECT_FUNCAO_ATIVIDADE';
const CF_SELECT_PALAVRA_CHAVE = 'CF_SELECT_TURMA_CRONOGRAMA';
const CF_SELECT_TIPO_ENCONTRO = 'CF_SELECT_TIPO_ENCONTRO';
const CF_SELECT_CRITERIO_CERTIFICACAO = 'CF_SELECT_CRITERIO_CERTIFICACAO';
const CF_SELECT_DRE = 'CF_SELECT_DRE';
const CF_SELECT_DRE_CADASTRO_PROPOSTAS = 'CF_SELECT_DRE_CADASTRO_PROPOSTAS';
const CF_SELECT_NOME_FORMACAO = 'CF_SELECT_NOME_FORMACAO';
const CF_SELECT_TIPO_INSCRICAO = 'CF_SELECT_TIPO_INSCRICAO';
const CF_SELECT_TIPO_EMAIL = 'CF_SELECT_TIPO_EMAIL';
const CF_SELECT_RESPONSAVEL_DF = 'CF_SELECT_RESPONSAVEL_DF';
const CF_SELECT_PARECERISTA = 'CF_SELECT_PARECERISTA';
const CF_SELECT_CARGA_HORARIA_TOTAL = 'CF_SELECT_CARGA_HORARIA_TOTAL';
const CF_SELECT_CARGA_HORARIA_TOTAL_OUTROS = 'CF_SELECT_CARGA_HORARIA_TOTAL';
const CF_SELECT_TIPO_NOTIFICACAO = 'CF_SELECT_TIPO_NOTIFICACAO';
const CF_SELECT_CATEGORIA_NOTIFICACAO = 'CF_SELECT_CATEGORIA_NOTIFICACAO';
const CF_SELECT_SITUACAO_NOTIFICACAO = 'CF_SELECT_SITUACAO_NOTIFICACAO';

export {
  CF_SELECT_ANO_ETAPA,
  CF_SELECT_AREA_PROMOTORA,
  CF_SELECT_CARGA_HORARIA_TOTAL,
  CF_SELECT_CARGA_HORARIA_TOTAL_OUTROS,
  CF_SELECT_CARGO,
  CF_SELECT_CATEGORIA_NOTIFICACAO,
  CF_SELECT_COMPONENTE_CURRICULAR,
  CF_SELECT_CRITERIOS_VALIDACOES_INSCRICAO,
  CF_SELECT_CRITERIO_CERTIFICACAO,
  CF_SELECT_DRE,
  CF_SELECT_DRE_CADASTRO_PROPOSTAS,
  CF_SELECT_FORMATO,
  CF_SELECT_FUNCAO_ATIVIDADE,
  CF_SELECT_FUNCAO_ESPECIFICA,
  CF_SELECT_MODALIDADE,
  CF_SELECT_NOME_FORMACAO,
  CF_SELECT_PALAVRA_CHAVE,
  CF_SELECT_PARECERISTA,
  CF_SELECT_PUBLICO_ALVO,
  CF_SELECT_RESPONSAVEL_DF,
  CF_SELECT_SITUACAO,
  CF_SELECT_SITUACAO_NOTIFICACAO,
  CF_SELECT_TIPO_EMAIL,
  CF_SELECT_TIPO_ENCONTRO,
  CF_SELECT_TIPO_INSCRICAO,
  CF_SELECT_TIPO_NOTIFICACAO,
  CF_SELECT_TURMA_CRONOGRAMA,
  CF_SELECT_TURMA_INSCRICAO,
  CF_SELECT_VAGAS_REMANESCENTES,
};
